# Generated by Django 5.2.15 on 2026-06-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="cashier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
