# Generated by Django 5.2.15 on 2026-06-17 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action", models.CharField(max_length=50)),
                ("entity", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("module_name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
