# Generated by Django 5.2.15 on 2026-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinestore",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
